src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
tests/Equinor.ProCoSys.BusSender.Core.Tests/BusSenderServiceTests.cs

Removing \r\n\t\f and then escaping.

Escaping characters

---

src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Topics/CommPkgTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/McPkgTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/TagTopic.cs

Added fields required for free-text-search subscriber.
Fields already exist in oracle triggers.
Bumped version number.

Added topic fields

---

src/Equinor.ProCoSys.BusSender.Infrastructure/Equinor.ProCoSys.BusSenderWorker.Infrastructure.csproj.user
src/Equinor.ProCoSys.PcsBus/Topics/PunchListItemTopic.cs

Misspelled class and filename. Corrected.

Corrected class and filename for PunchListItemTopic

---

src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj

Typo fix punch list item topic

---

src/Equinor.ProCoSys.PcsBus/PcsTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/TagTopic.cs

add new properties to tag topic and add punchlistitem pcstopic

85769 update with new fam additions

---

src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj

forgot to bump version in previous pr

bump version 

---

src/Equinor.ProCoSys.PcsBus/Topics/McPkgTopic.cs

Add mcstatus and milestones to mcpkg topic. They've already been added to trigger.

84477 - Add mcstatus and milestones to mcpkg topic

---

src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.BusSender.Worker/appsettings.json
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Topics/MilestoneTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/WorkOrderTopic.cs

[AB#88839](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88839)

88839-Add milestone topic

---

src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.BusSender.Worker/appsettings.json
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/PcsTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/CommPkgTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/WorkOrderCutoffTopic.cs

[AB#88778](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88778)

WoCuttoff topic

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/PcsTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/WorkOrderTopic.cs

[AB#88878](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/88878)

remove subobjects from WO and add WoChecklist. 

---

src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Topics/ChecklistTopic.cs

- added revision to checklist
-  -updated version to .28

Updated Checklist

---

PcsServiceBus.sln.DotSettings.user
src/Equinor.ProCoSys.BusSender.Core/Interfaces/ITagDetailsRepository.cs
src/Equinor.ProCoSys.BusSender.Core/Models/BusEvent.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/EntryPointService.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Data/BusSenderServiceContext.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/EntityConfiguration/BusEventConfiguration.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/BlobRepository.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/BusEventRepository.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/TagDetailsRepository.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/ServiceCollectionSetup.cs
src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.BusSender.Worker/Program.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Topics/TagTopic.cs
tests/Equinor.ProCoSys.BusSender.Core.Tests/BusSenderServiceTests.cs
tests/Equinor.ProCoSys.BusSender.Infrastructure.Tests/BusEventRepositoryTests.cs
tests/Equinor.ProCoSys.BusSender.Infrastructure.Tests/ContextHelper.cs

[AB#89084](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/89084)

89084 Tag details in busService instead of trigger

---

src/Equinor.ProCoSys.BusSender.Core/Models/WoMaterialIdentifier.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Core/Status.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/BusEventRepository.cs
src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.BusSender.Worker/Program.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/PcsTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/StockTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/WoMaterialTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/WoMilestoneTopic.cs

[AB#90163](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/90163)

90163 wo material wo milestone stock

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj

Document topic

---

src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/ChecklistQuery.cs
src/Equinor.ProCoSys.PcsBus/Queries/MilestonesQuery.cs

Previous pullrequest was merged to main, so this fixes the error and merges everything. to Dev

#bug232378 milestone update

---

src/Equinor.ProCoSys.PcsBus/Topics/CertificateTopic.cs

[AB#95536](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95536)

95536 - Equinor.ProCoSys.PcsServiceBus.Topics.CertificateTopic.ProCoSysGuid

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/CommPkgQuery.cs

[AB#95727](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/95727)

95727 - Add Progress field to CommPkg message

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/ChecklistQuery.cs

[AB#96357](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96357)

96357. Minor checklist fix and bump

---

src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusSenderMessageRepository.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/BusSenderMessageRepository.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/CommPkgTaskQuery.cs
src/Equinor.ProCoSys.PcsBus/Queries/TaskQuery.cs
src/Equinor.ProCoSys.PcsBus/Topics/CommPkgTaskTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/TaskTopic.cs

Changed grouping in FilterOnSimpleMessagesAndGroupDuplicates from long to string in order to support combined id's

96363 task to servicebus worker

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/ChecklistQuery.cs

[AB#96357](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96357)
Doing this against master separately since we're not in a good place :/

96357 master patch

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Topics/CertificateTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/CommPkgTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/IpoTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/LibraryTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/McPkgTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/ProjectTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/ResponsibleTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/TagFunctionTopic.cs
src/Equinor.ProCoSys.PcsBus/Topics/TagTopic.cs

[AB#96688](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96688)

96688 expand topics to include behavior and guid

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/TaskQuery.cs

PBI: 98432 CommPkg_Actions to FAM add TaskId (245196)

Added TaskID to TaskQuery

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/QuerySignatureQuery.cs

Add status.code and librarystatusguid to query signature.
[AB#98571](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/98571)

98571 - Add status to querysignature

---

src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/TagDetailsRepository.cs
src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj.user
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/TagQuery.cs

[AB#100798](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/100798)

100798 - Add FromTagGuid and ToTagGuid in TagDetails

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/TagQuery.cs

[AB#100940](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/100940)

100940 - Incorrect guid format fromtagguid totagguid

---

src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/BusSenderMessageRepository.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/TagDetailsRepository.cs

[AB#102505](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/102505)

close connection if opening, and do it in a finally block

---

PcsServiceBus.sln.DotSettings
src/Equinor.ProCoSys.BusSender.Core/Equinor.ProCoSys.BusSenderWorker.Core.csproj
src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Models/ActionEvent.cs
src/Equinor.ProCoSys.BusSender.Core/Models/HeatTracePipeTestEvent.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.PcsBus/Interfaces/IHeatTracePipeTestEventV1.cs
src/Equinor.ProCoSys.PcsBus/PcsEventConstants.cs
src/Equinor.ProCoSys.PcsBus/Queries/HeatTracePipeTestQuery.cs
tests/Equinor.ProCoSys.BusSender.Core.Tests/BusEventServiceTests.cs
tests/Equinor.ProCoSys.BusSender.Infrastructure.Tests/Equinor.ProCoSys.BusSenderWorker.Infrastructure.Tests.csproj
tests/Equinor.ProCoSys.BusSender.Infrastructure.Tests/HandlerTests.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/ActionEventTests.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/HeatTracePipeTestEventTests.cs
tests/Equinor.ProCoSys.PcsBusTests/QueryTests.cs

[AB#103047](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/103047)

Add HeatTracePipeTestEvent with code and tests

---

src/Equinor.ProCoSys.PcsBus/Enums/CertificateStatus.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj

[AB#105340](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/105340)

105340 Add new certificate status

---

src/Equinor.ProCoSys.BusSender.Core/Models/BusEventMessage.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Core/Telemetry/ApplicationInsightsTelemetryClient.cs
src/Equinor.ProCoSys.BusSender.Core/Telemetry/ITelemetryClient.cs

[AB#107253](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/107253)
@Digipix fyi.

107253: cleaned up logging

---

src/Equinor.ProCoSys.BusReceiver/Equinor.ProCoSys.BusReceiver.csproj
src/Equinor.ProCoSys.BusReceiver/Program.cs
src/Equinor.ProCoSys.BusSender.Core/Equinor.ProCoSys.BusSenderWorker.Core.csproj
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Equinor.ProCoSys.BusSenderWorker.Infrastructure.csproj
src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
tests/Equinor.ProCoSys.BusSender.Core.Tests/Equinor.ProCoSys.BusSenderWorker.Core.Tests.csproj
tests/Equinor.ProCoSys.BusSender.Infrastructure.Tests/Equinor.ProCoSys.BusSenderWorker.Infrastructure.Tests.csproj
tests/Equinor.ProCoSys.PcsBusTests/Equinor.ProCoSys.PcsServiceBusTests.csproj

[AB#96314](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/96314)

96314_upgrade nuget packages

---

src/Equinor.ProCoSys.BusSender.Core/Models/SwcrSignatureEvent.cs
src/Equinor.ProCoSys.PcsBus/Interfaces/ISwcrSignatureEventV1.cs
src/Equinor.ProCoSys.PcsBus/Queries/SwcrSignatureQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/SwcrSignatureEventTests.cs

[AB#108852](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/108852)

108852_Add swcr status code to swcrSignature

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/ProjectQuery.cs

[AB#109159](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/109159)

Hotfix - 109159 - BusSender fails to process thin project messages

---

src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Models/PersonEvent.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/EventRepository.cs
src/Equinor.ProCoSys.BusSender.Worker/appsettings.json
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/IPersonEventV1.cs
src/Equinor.ProCoSys.PcsBus/PcsEventConstants.cs
src/Equinor.ProCoSys.PcsBus/Queries/PersonQuery.cs
src/Equinor.ProCoSys.PcsBus/Topics/PersonTopic.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/PersonEventTests.cs
tests/Equinor.ProCoSys.PcsBusTests/QueryTests.cs

[AB#109033](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/109033)

109033: Create person messages on bus

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/WorkOrderCutoffQuery.cs

[AB#112166](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/112166)

112166: Changed source of wo_cutoff to ensure that new range concept is handled.

---

src/Equinor.ProCoSys.BusSender.Core/Models/PunchListItemEvent.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/IPunchListItemEventV1.cs
src/Equinor.ProCoSys.PcsBus/Queries/PunchListItemQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/PunchListItemEventTests.cs

[AB#112672](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/112672)

Added guid for project

---

src/Equinor.ProCoSys.BusSender.Core/Models/DocumentEvent.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/IDocumentEventV1.cs
src/Equinor.ProCoSys.PcsBus/Queries/DocumentQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/DocumentEventTests.cs

[AB#113806](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/113806)

Added isVoided to document event

---

src/Equinor.ProCoSys.BusSender.Core/Models/PunchListItemEvent.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/IPunchListItemEventV1.cs
src/Equinor.ProCoSys.PcsBus/Queries/PunchListItemQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/PunchListItemEventTests.cs

[AB#113819](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/113819)

Added person guids

---

src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Models/NotificationWorkOrderEvent.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/INotificationWorkOrderEventV1.cs
src/Equinor.ProCoSys.PcsBus/PcsEventConstants.cs
src/Equinor.ProCoSys.PcsBus/PcsTopicConstants.cs
src/Equinor.ProCoSys.PcsBus/Queries/NotificationWorkOrderQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/NotificationWorkOrderEventTests.cs

[AB#114637](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/114637)

114637 Send data to ServiceBus for NotificationWorkOrder

---

src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Models/NotificationCommPkgEvent.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/INotificationCommPkgEventV1.cs
src/Equinor.ProCoSys.PcsBus/PcsEventConstants.cs
src/Equinor.ProCoSys.PcsBus/PcsTopicConstants.cs
src/Equinor.ProCoSys.PcsBus/Queries/NotificationCommPkgBoundaryQuery.cs
src/Equinor.ProCoSys.PcsBus/Queries/NotificationCommPkgOtherQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/NotificationCommPkgEventTest.cs
tests/Equinor.ProCoSys.PcsBusTests/QueryTests.cs

[AB#114647](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/114647)

114647 Send Notification CommPkgs to ServiceBus

---

src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Models/NotificationCommPkgEvent.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusEventService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/INotificationCommPkgEventV1.cs
src/Equinor.ProCoSys.PcsBus/PcsEventConstants.cs
src/Equinor.ProCoSys.PcsBus/PcsTopicConstants.cs
src/Equinor.ProCoSys.PcsBus/Queries/NotificationCommPkgBoundaryQuery.cs
src/Equinor.ProCoSys.PcsBus/Queries/NotificationCommPkgOtherQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/NotificationCommPkgEventTest.cs
tests/Equinor.ProCoSys.PcsBusTests/QueryTests.cs

[AB#114647](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/114647)
* Added NotificationCommPkg
* Add RelationshipType to queries. Add unit test for event interface
* Up version
* Add Testdata for NotificationCommPkg

114647 Send Notification CommPkgs to ServiceBus (#133)

---

src/Equinor.ProCoSys.BusSender.Core/Models/NotificationEvent.cs
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Interfaces/INotificationEventV1.cs
src/Equinor.ProCoSys.PcsBus/Queries/NotificationQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/NotificationEventTest.cs

[AB#115611](https://statoildeveloper.visualstudio.com/b6d97460-2e53-47ae-aad4-b41396d90828/_workitems/edit/115611)

115611 Send more fields for notification

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/NotificationSignatureQuery.cs

https://github.com/equinor/cc-toolbox/issues/451

451 - NotificationSignature NotificationGuid does not point to Notification

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Queries/NotificationSignatureQuery.cs

https://github.com/equinor/cc-toolbox/issues/451

Merge dev to master (451)

---

src/Equinor.ProCoSys.BusSender.Core/Interfaces/IBusEventRepository.cs
src/Equinor.ProCoSys.BusSender.Core/Interfaces/IQueueMonitorService.cs
src/Equinor.ProCoSys.BusSender.Core/Interfaces/ISystemClock.cs
src/Equinor.ProCoSys.BusSender.Core/Services/BusSenderService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/QueueMonitorService.cs
src/Equinor.ProCoSys.BusSender.Core/Services/TimeService.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/Repositories/BusEventRepository.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/ServiceCollectionSetup.cs
tests/Equinor.ProCoSys.BusSender.Core.Tests/BusSenderServiceTests.cs
tests/Equinor.ProCoSys.BusSender.Core.Tests/Equinor.ProCoSys.BusSenderWorker.Core.Tests.csproj
tests/Equinor.ProCoSys.BusSender.Core.Tests/ManualTImeProvider.cs
tests/Equinor.ProCoSys.BusSender.Core.Tests/QueueMonitorServiceTests.cs

https://github.com/equinor/cc-toolbox/issues/674

Merge dev to master (674)

---

src/Equinor.ProCoSys.BusSender.Core/Models/BusEvent.cs
src/Equinor.ProCoSys.BusSender.Infrastructure/EntityConfiguration/BusEventConfiguration.cs
tests/Equinor.ProCoSys.BusSender.Core.Tests/BusSenderServiceTests.cs
tests/Equinor.ProCoSys.BusSender.Infrastructure.Tests/BusEventRepositoryTests.cs

https://github.com/equinor/cc-toolbox/issues/690
https://github.com/equinor/cc-toolbox/issues/686

Added PROJECTSCHEMA column to the BUSEVENT table/model

---

src/Equinor.ProCoSys.BusSender.Core/Models/WorkOrderMaterialEvent.cs
src/Equinor.ProCoSys.PcsBus/Interfaces/IWorkOrderMaterialEventV1.cs
src/Equinor.ProCoSys.PcsBus/Queries/WorkOrderMaterialQuery.cs
tests/Equinor.ProCoSys.PcsBusTests/EventVersioningTests/WorkOrderMaterialEventTests.cs

https://github.com/equinor/cc-toolbox/issues/946

added stock guid to wo_material

---

azure-pipeline.yml
src/Equinor.ProCoSys.BusReceiver/Dockerfile
src/Equinor.ProCoSys.BusReceiver/Equinor.ProCoSys.BusReceiver.csproj
src/Equinor.ProCoSys.BusSender.Core/Equinor.ProCoSys.BusSenderWorker.Core.csproj
src/Equinor.ProCoSys.BusSender.Infrastructure/Equinor.ProCoSys.BusSenderWorker.Infrastructure.csproj
src/Equinor.ProCoSys.BusSender.Worker/Dockerfile
src/Equinor.ProCoSys.BusSender.Worker/Equinor.ProCoSys.BusSender.Worker.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.nuspec
tests/Equinor.ProCoSys.BusSender.Core.Tests/Equinor.ProCoSys.BusSenderWorker.Core.Tests.csproj
tests/Equinor.ProCoSys.BusSender.Infrastructure.Tests/Equinor.ProCoSys.BusSenderWorker.Infrastructure.Tests.csproj
tests/Equinor.ProCoSys.PcsBusTests/Equinor.ProCoSys.PcsServiceBusTests.csproj

https://github.com/equinor/cc-toolbox/issues/598

598 Update to .NET 8

---

src/Equinor.ProCoSys.PcsBus/Equinor.ProCoSys.PcsServiceBus.csproj
src/Equinor.ProCoSys.PcsBus/IServiceCollectionExtensions.cs
src/Equinor.ProCoSys.PcsBus/PcsServiceBusConfig.cs

Adding the option to authenticate the service bus client with token credentials.
https://github.com/equinor/cc-toolbox/issues/1065

1065 client credential authentication option
